# Gemspec

Gemspec/AddRuntimeDependency:
  Enabled: true

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: true

Gemspec/RequireMFA:
  Enabled: true

# Layout

Layout/LineLength:
  Max: 120

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineContinuationLeadingSpace:
  Enabled: true

Layout/LineContinuationSpacing:
  Enabled: true

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

# Lint

Lint/DuplicateMethods:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/AmbiguousAssignment: # new in 1.7
  Enabled: true

Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: true

Lint/AmbiguousRange: # new in 1.19
  Enabled: true

Lint/ConstantOverwrittenInRescue: # new in 1.31
  Enabled: true

Lint/DeprecatedConstants: # new in 1.8
  Enabled: true

Lint/DuplicateBranch: # new in 1.3
  Enabled: true

Lint/DuplicateMagicComment: # new in 1.37
  Enabled: true

Lint/DuplicateMatchPattern: # new in 1.50
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement: # new in 1.1
  Enabled: true

Lint/DuplicateSetElement: # new in 1.67
  Enabled: true

Lint/EmptyBlock: # new in 1.1
  Enabled: true

Lint/EmptyClass: # new in 1.3
  Enabled: true

Lint/EmptyInPattern: # new in 1.16
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: true

Lint/ItWithoutArgumentsInBlock: # new in 1.59
  Enabled: true

Lint/LambdaWithoutLiteralBlock: # new in 1.8
  Enabled: true

Lint/LiteralAssignmentInCondition: # new in 1.58
  Enabled: true

Lint/MixedCaseRange: # new in 1.53
  Enabled: true

Lint/NoReturnInBeginEndBlocks: # new in 1.2
  Enabled: true

Lint/NonAtomicFileOperation: # new in 1.31
  Enabled: true

Lint/NumberedParameterAssignment: # new in 1.9
  Enabled: true

Lint/OrAssignmentToConstant: # new in 1.9
  Enabled: true

Lint/RedundantDirGlobSort: # new in 1.8
  Enabled: true

Lint/RedundantRegexpQuantifiers: # new in 1.53
  Enabled: true

Lint/RefinementImportMethods: # new in 1.27
  Enabled: true

Lint/RequireRangeParentheses: # new in 1.32
  Enabled: true

Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: true

Lint/SymbolConversion: # new in 1.9
  Enabled: true

Lint/ToEnumArguments: # new in 1.1
  Enabled: true

Lint/TripleQuotes: # new in 1.9
  Enabled: true

Lint/UnescapedBracketInRegexp: # new in 1.68
  Enabled: true

Lint/UnexpectedBlockArity: # new in 1.5
  Enabled: true

Lint/UnmodifiedReduceAccumulator: # new in 1.1
  Enabled: true

Lint/UselessNumericOperation: # new in 1.66
  Enabled: true

Lint/UselessRescue: # new in 1.43
  Enabled: true

Lint/UselessRuby2Keywords: # new in 1.23
  Enabled: true

# Metrics

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Max: 300

Metrics/CollectionLiteralLength:
  Enabled: true

# Naming

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/BlockForwarding:
  Enabled: true

# Security

Security/CompoundHash:
  Enabled: true

Security/IoMethods:
  Enabled: true

# Style

Style/Documentation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RedundantCapitalW:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/AmbiguousEndlessMethodDefinition:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/ArrayIntersect:
  Enabled: true

Style/BitwisePredicate:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/CombinableDefined:
  Enabled: true

Style/ComparableClamp:
  Enabled: true

Style/ConcatArrayLiterals:
  Enabled: true

Style/DataInheritance:
  Enabled: true

Style/DirEmpty:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/EmptyHeredoc:
  Enabled: true

Style/EndlessMethod:
  Enabled: true

Style/EnvHome:
  Enabled: true

Style/ExactRegexpMatch:
  Enabled: true

Style/FetchEnvVar:
  Enabled: true

Style/FileEmpty:
  Enabled: true

Style/FileRead:
  Enabled: true

Style/FileWrite:
  Enabled: true

Style/HashConversion:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/InPatternThen:
  Enabled: true

Style/KeywordArgumentsMerging:
  Enabled: true

Style/MagicCommentFormat:
  Enabled: true

Style/MapCompactWithConditionalBlock:
  Enabled: true

Style/MapIntoArray:
  Enabled: true

Style/MapToHash:
  Enabled: true

Style/MapToSet:
  Enabled: true

Style/MinMaxComparison:
  Enabled: true

Style/MultilineInPatternThen:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/NestedFileDirname:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/NumberedParameters:
  Enabled: true

Style/NumberedParametersLimit:
  Enabled: true

Style/ObjectThen:
  Enabled: true

Style/OpenStructUse:
  Enabled: true

Style/OperatorMethodCall:
  Enabled: true

Style/QuotedSymbols:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Style/RedundantArrayConstructor:
  Enabled: true

Style/RedundantConstantBase:
  Enabled: true

Style/RedundantCurrentDirectoryInPath:
  Enabled: true

Style/RedundantDoubleSplatHashBraces:
  Enabled: true

Style/RedundantEach:
  Enabled: true

Style/RedundantFilterChain:
  Enabled: true

Style/RedundantHeredocDelimiterQuotes:
  Enabled: true

Style/RedundantInitialize:
  Enabled: true

Style/RedundantInterpolationUnfreeze:
  Enabled: true

Style/RedundantLineContinuation:
  Enabled: true

Style/RedundantRegexpArgument:
  Enabled: true

Style/RedundantRegexpConstructor:
  Enabled: true

Style/RedundantSelfAssignmentBranch:
  Enabled: true

Style/RedundantStringEscape:
  Enabled: true

Style/ReturnNilInPredicateMethodDefinition:
  Enabled: true

Style/SafeNavigationChainLength:
  Enabled: true

Style/SelectByRegexp:
  Enabled: true

Style/SendWithLiteralMethodName:
  Enabled: true

Style/SingleLineDoEndBlock:
  Enabled: true

Style/StringChars:
  Enabled: true

Style/SuperArguments:
  Enabled: true

Style/SuperWithArgsParentheses:
  Enabled: true

Style/SwapValues:
  Enabled: true

Style/YAMLFileRead:
  Enabled: true