tree-sitter-version = "0.24.4"

[parsers]
java = "0.23.2"
kotlin = { ref = "76f53c48d29e8588934fb55b0240d7bdfe00bfe5", from = "https://github.com/fwcd/tree-sitter-kotlin" }
swift = { ref = "6accc2f720c7ff8573f6956a34ea22f50c44d839", from = "https://github.com/alex-pinkus/tree-sitter-swift" }
objc = { ref = "62e61b6f5c0289c376d61a8c91faf6435cde9012", from = "https://github.com/tree-sitter-grammars/tree-sitter-objc", cmd = "npm install && node install && node build"}