name: CLI Tests and Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rubocop --parallel

  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby-version: ['3.2.2']
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run Minitest tests
        run: |
          bundle exec rake test TESTOPTS="--verbose"
        env:
          MINITEST_REPORTER: ProgressReporter
